name: KBOT-CICD

on:
  push:
    branches:
      - develop
env:
  TARGETOS: linux
  TARGETARCH: amd64

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test
        run: make test

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: "ghcr.io/ashyshka"
        run: make image push
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        GITTAG=$(git describe --tags --abbrev=0 --always)
        if [ $GITTAG == "" ]
        then
          echo "APPTAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "CHARTVERSION=0.0.0" >> $GITHUB_ENV
        else
          echo "APPTAG=$(git describe --tags --abbrev=0 --always)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "CHARTVERSION=$(git describe --tags --abbrev=0 --always)" >> $GITHUB_ENV
        fi
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(APPTAG) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.appVersion=strenv(APPTAG) | .version=strenv(CHARTVERSION)' helm/Chart.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push
